[project]
name = "malt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymc[nutpie]>=6.3.2",
    "scikit-learn>=1.9.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/malt"]

[dependency-groups]
dev = [
    "matplotlib>=3.11.2",
    "pytest>=9.1.1",
]

[tool.pyright]
typeCheckingMode = "standard"
